repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      # Fix imports
      - id: ruff
        args: ["--fix", "--select", "I"]
      # Linter (with fix)
      - id: ruff
        args: ["--fix"]
      # Formatter
      - id: ruff-format
        types_or: ["python"]
      - id: codespell
        name: 📝 Check code for common misspellings
        language: system
        types: [text]
        pass_filenames: false
      - id: end-of-file-fixer
        name: 🧹 Fix End of Files
        language: system
        types: [text]

